// Processed municipality data from the CSV
export const municipalityData = [
  // Metropolitan Cities
  { name: "Kathmandu", type: "Metropolitan City", wards: 32 },
  { name: "Pokhara", type: "Metropolitan City", wards: 33 },
  { name: "Biratnagar", type: "Metropolitan City", wards: 19 },
  { name: "Lalitpur", type: "Metropolitan City", wards: 29 },
  { name: "Bharatpur", type: "Metropolitan City", wards: 29 },
  { name: "Birgunj", type: "Metropolitan City", wards: 32 },

  // Sub-Metropolitan Cities
  { name: "Janakpur", type: "Sub-Metropolitan City", wards: 25 },
  { name: "Ghorahi", type: "Sub-Metropolitan City", wards: 19 },
  { name: "Hetauda", type: "Sub-Metropolitan City", wards: 19 },
  { name: "Dhangadhi", type: "Sub-Metropolitan City", wards: 19 },
  { name: "Tulsipur", type: "Sub-Metropolitan City", wards: 19 },
  { name: "Itahari", type: "Sub-Metropolitan City", wards: 20 },
  { name: "Nepalgunj", type: "Sub-Metropolitan City", wards: 23 },
  { name: "Butwal", type: "Sub-Metropolitan City", wards: 19 },
  { name: "Dharan", type: "Sub-Metropolitan City", wards: 20 },
  { name: "Kalaiya", type: "Sub-Metropolitan City", wards: 27 },
  { name: "Jitpur-Simara", type: "Sub-Metropolitan City", wards: 24 },

  // Municipalities
  { name: "Mangalsen", type: "Municipality", wards: 14 },
  { name: "Panchadewal Binayak", type: "Municipality", wards: 9 },
  { name: "Sanphebagar", type: "Municipality", wards: 14 },
  { name: "Kamalbazar", type: "Municipality", wards: 10 },
  { name: "Sandhikharka", type: "Municipality", wards: 12 },
  { name: "Sitganga", type: "Municipality", wards: 14 },
  { name: "Bhumikasthan", type: "Municipality", wards: 10 },
  { name: "Baglung", type: "Municipality", wards: 14 },
  { name: "Galkot", type: "Municipality", wards: 11 },
  { name: "Dhorpatan", type: "Municipality", wards: 9 },
  { name: "Jaimini", type: "Municipality", wards: 10 },
  { name: "Puchaudi", type: "Municipality", wards: 10 },
  { name: "Dasharathchand", type: "Municipality", wards: 11 },
  { name: "Patan", type: "Municipality", wards: 10 },
  { name: "Melauli", type: "Municipality", wards: 9 },
  { name: "Bungal", type: "Municipality", wards: 11 },
  { name: "Jaya Prithvi", type: "Municipality", wards: 11 },
  { name: "Budhiganga", type: "Municipality", wards: 10 },
  { name: "Budhinanda", type: "Municipality", wards: 10 },
  { name: "Badimalika", type: "Municipality", wards: 9 },
  { name: "Tribeni", type: "Municipality", wards: 9 },
  { name: "Kohalpur", type: "Municipality", wards: 15 },
  { name: "Mahagadhimai", type: "Municipality", wards: 11 },
  { name: "Simraungadh", type: "Municipality", wards: 11 },
  { name: "Kolhabi", type: "Municipality", wards: 11 },
  { name: "Pacharauta", type: "Municipality", wards: 9 },
  { name: "Nijgadh", type: "Municipality", wards: 13 },
  { name: "Gulariya", type: "Municipality", wards: 12 },
  { name: "Barbardiya", type: "Municipality", wards: 11 },
  { name: "Bansgadhi", type: "Municipality", wards: 9 },
  { name: "Rajapur", type: "Municipality", wards: 10 },
  { name: "Madhuwan", type: "Municipality", wards: 9 },
  { name: "Thakurbaba", type: "Municipality", wards: 9 },
  { name: "Suryabinayak", type: "Municipality", wards: 10 },
  { name: "Madhyapur Thimi", type: "Municipality", wards: 9 },
  { name: "Changunarayan", type: "Municipality", wards: 9 },
  { name: "Bhaktapur", type: "Municipality", wards: 10 },
  { name: "Shadananda", type: "Municipality", wards: 14 },
  { name: "Bhojpur", type: "Municipality", wards: 12 },
  { name: "Ratnanagar", type: "Municipality", wards: 16 },
  { name: "Khairhani", type: "Municipality", wards: 13 },
  { name: "Rapti", type: "Municipality", wards: 13 },
  { name: "Kalika", type: "Municipality", wards: 11 },
  { name: "Madi", type: "Municipality", wards: 9 },
  { name: "Parshuram", type: "Municipality", wards: 12 },
  { name: "Amargadhi", type: "Municipality", wards: 11 },
  { name: "Dullu", type: "Municipality", wards: 13 },
  { name: "Aathabis", type: "Municipality", wards: 9 },
  { name: "Chamunda Bindrasaini", type: "Municipality", wards: 9 },
  { name: "Narayan", type: "Municipality", wards: 11 },
  { name: "Lamahi", type: "Municipality", wards: 9 },
  { name: "Mahakali", type: "Municipality", wards: 9 },
  { name: "Shailyashikhar", type: "Municipality", wards: 9 },
  { name: "Nilkantha", type: "Municipality", wards: 14 },
  { name: "Dhunibeshi", type: "Municipality", wards: 9 },
  { name: "Dhankuta", type: "Municipality", wards: 10 },
  { name: "Mahalaxmi", type: "Municipality", wards: 9 },
  { name: "Pakhribas", type: "Municipality", wards: 10 },
  { name: "Mithila Bihari", type: "Municipality", wards: 10 },
  { name: "Sabaila", type: "Municipality", wards: 13 },
  { name: "Shahidnagar", type: "Municipality", wards: 9 },
  { name: "Dhanushadham", type: "Municipality", wards: 9 },
  { name: "Chhireshwarnath", type: "Municipality", wards: 10 },
  { name: "Mithila", type: "Municipality", wards: 11 },
  { name: "Hansapur", type: "Municipality", wards: 9 },
  { name: "Kamala", type: "Municipality", wards: 9 },
  { name: "Ganeshman Charanath", type: "Municipality", wards: 11 },
  { name: "Nagarain", type: "Municipality", wards: 9 },
  { name: "Bideha", type: "Municipality", wards: 9 },
  { name: "Bhimeshwar", type: "Municipality", wards: 9 },
  { name: "Jiri", type: "Municipality", wards: 9 },
  { name: "Tripura Sundari", type: "Municipality", wards: 11 },
  { name: "Thuli Bheri", type: "Municipality", wards: 11 },
  { name: "Dipayal Silgadhi", type: "Municipality", wards: 9 },
  { name: "Shikhar", type: "Municipality", wards: 11 },
  { name: "Gorkha", type: "Municipality", wards: 14 },
  { name: "Palungtar", type: "Municipality", wards: 10 },
  { name: "Resunga", type: "Municipality", wards: 14 },
  { name: "Musikot", type: "Municipality", wards: 9 },
  { name: "Suryodaya", type: "Municipality", wards: 14 },
  { name: "Ilam", type: "Municipality", wards: 10 },
  { name: "Deumai", type: "Municipality", wards: 9 },
  { name: "Mai", type: "Municipality", wards: 10 },
  { name: "Bheri", type: "Municipality", wards: 13 },
  { name: "Chhedagad", type: "Municipality", wards: 13 },
  { name: "Nalgad", type: "Municipality", wards: 13 },
  { name: "Mechinagar", type: "Municipality", wards: 15 },
  { name: "Birtamod", type: "Municipality", wards: 10 },
  { name: "Damak", type: "Municipality", wards: 10 },
  { name: "Arjundhara", type: "Municipality", wards: 11 },
  { name: "Shivasatakshi", type: "Municipality", wards: 11 },
  { name: "Bhadrapur", type: "Municipality", wards: 10 },
  { name: "Gauradaha", type: "Municipality", wards: 9 },
  { name: "Kankai", type: "Municipality", wards: 9 },
  { name: "Chandannath", type: "Municipality", wards: 10 },
  { name: "Godawari", type: "Municipality", wards: 12 },
  { name: "Lamki Chuha", type: "Municipality", wards: 10 },
  { name: "Tikapur", type: "Municipality", wards: 9 },
  { name: "Ghodaghodi", type: "Municipality", wards: 12 },
  { name: "Gauriganga", type: "Municipality", wards: 11 },
  { name: "Bhajani", type: "Municipality", wards: 9 },
  { name: "Khandachakra", type: "Municipality", wards: 11 },
  { name: "Raskot", type: "Municipality", wards: 9 },
  { name: "Tilagupha", type: "Municipality", wards: 11 },
  { name: "Bhimdatta", type: "Municipality", wards: 19 },
  { name: "Krishnapur", type: "Municipality", wards: 9 },
  { name: "Punarbas", type: "Municipality", wards: 11 },
  { name: "Bedkot", type: "Municipality", wards: 10 },
  { name: "Shuklaphanta", type: "Municipality", wards: 12 },
  { name: "Belauri", type: "Municipality", wards: 10 },
  { name: "Dodhara Chandani", type: "Municipality", wards: 10 },
  { name: "Banganga", type: "Municipality", wards: 11 },
  { name: "Kapilvastu", type: "Municipality", wards: 12 },
  { name: "Shivaraj", type: "Municipality", wards: 11 },
  { name: "Buddhabhumi", type: "Municipality", wards: 10 },
  { name: "Krishnanagar", type: "Municipality", wards: 12 },
  { name: "Maharajganj", type: "Municipality", wards: 11 },
  { name: "Budhanilkantha", type: "Municipality", wards: 13 },
  { name: "Tarakeshwar", type: "Municipality", wards: 11 },
  { name: "Gokarneshwar", type: "Municipality", wards: 9 },
  { name: "Chandragiri", type: "Municipality", wards: 15 },
  { name: "Tokha", type: "Municipality", wards: 11 },
  { name: "Kageshwari-Manohara", type: "Municipality", wards: 9 },
  { name: "Nagarjun", type: "Municipality", wards: 10 },
  { name: "Kirtipur", type: "Municipality", wards: 10 },
  { name: "Shankharapur", type: "Municipality", wards: 9 },
  { name: "Dakshinkali", type: "Municipality", wards: 9 },
  { name: "Banepa", type: "Municipality", wards: 14 },
  { name: "Paunauti", type: "Municipality", wards: 12 },
  { name: "Panchkhal", type: "Municipality", wards: 13 },
  { name: "Dhulikhel", type: "Municipality", wards: 12 },
  { name: "Mandan Deupur", type: "Municipality", wards: 12 },
  { name: "Namobuddha", type: "Municipality", wards: 11 },
  { name: "Diktel Rupakot Majhuwagadhi", type: "Municipality", wards: 15 },
  { name: "Halesi Tuwachung", type: "Municipality", wards: 11 },
  { name: "Mahalaxmi", type: "Municipality", wards: 10 },
  { name: "Godawari", type: "Municipality", wards: 14 },
  { name: "Besisahar", type: "Municipality", wards: 11 },
  { name: "Sundarbazar", type: "Municipality", wards: 11 },
  { name: "Madhya Nepal", type: "Municipality", wards: 10 },
  { name: "Rainas", type: "Municipality", wards: 10 },
  { name: "Bardibas", type: "Municipality", wards: 14 },
  { name: "Gaushala", type: "Municipality", wards: 12 },
  { name: "Jaleshwar", type: "Municipality", wards: 12 },
  { name: "Bhangaha", type: "Municipality", wards: 9 },
  { name: "Manara Shiswa", type: "Municipality", wards: 10 },
  { name: "Balawa", type: "Municipality", wards: 11 },
  { name: "Loharpatti", type: "Municipality", wards: 9 },
  { name: "Aurahi", type: "Municipality", wards: 9 },
  { name: "Ramgopalpur", type: "Municipality", wards: 9 },
  { name: "Matihani", type: "Municipality", wards: 9 },
  { name: "Thaha", type: "Municipality", wards: 12 },
  { name: "Sundar Haraincha", type: "Municipality", wards: 12 },
  { name: "Belbari", type: "Municipality", wards: 11 },
  { name: "Pathari Shanischare", type: "Municipality", wards: 10 },
  { name: "Urlabari", type: "Municipality", wards: 9 },
  { name: "Ratuwamai", type: "Municipality", wards: 10 },
  { name: "Rangeli", type: "Municipality", wards: 9 },
  { name: "Sunawarshi", type: "Municipality", wards: 9 },
  { name: "Letang", type: "Municipality", wards: 9 },
  { name: "Chhayanath Rara", type: "Municipality", wards: 14 },
  { name: "Beni", type: "Municipality", wards: 10 },
  { name: "Bardaghat", type: "Municipality", wards: 16 },
  { name: "Kawasoti", type: "Municipality", wards: 17 },
  { name: "Gaindakot", type: "Municipality", wards: 18 },
  { name: "Madhyabindu", type: "Municipality", wards: 15 },
  { name: "Devchuli", type: "Municipality", wards: 17 },
  { name: "Bidur", type: "Municipality", wards: 13 },
  { name: "Belkotgadhi", type: "Municipality", wards: 13 },
  { name: "Siddhicharan", type: "Municipality", wards: 12 },
  { name: "Tansen", type: "Municipality", wards: 14 },
  { name: "Rampur", type: "Municipality", wards: 10 },
  { name: "Phidim", type: "Municipality", wards: 14 },
  { name: "Sunawal", type: "Municipality", wards: 13 },
  { name: "Ramgram", type: "Municipality", wards: 18 },
  { name: "Kushma", type: "Municipality", wards: 14 },
  { name: "Phalebas", type: "Municipality", wards: 11 },
  { name: "Bahudarmai", type: "Municipality", wards: 9 },
  { name: "Parsagadhi", type: "Municipality", wards: 9 },
  { name: "Pokhariya", type: "Municipality", wards: 10 },
  { name: "Pyuthan", type: "Municipality", wards: 10 },
  { name: "Swargadwari", type: "Municipality", wards: 9 },
  { name: "Manthali", type: "Municipality", wards: 14 },
  { name: "Ramechhap", type: "Municipality", wards: 9 },
  { name: "Chandrapur", type: "Municipality", wards: 10 },
  { name: "Garuda", type: "Municipality", wards: 9 },
  { name: "Rajpur", type: "Municipality", wards: 9 },
  { name: "Gujara", type: "Municipality", wards: 9 },
  { name: "Ishnath", type: "Municipality", wards: 9 },
  { name: "Brindaban", type: "Municipality", wards: 9 },
  { name: "Gadhimai", type: "Municipality", wards: 9 },
  { name: "Katahariya", type: "Municipality", wards: 9 },
  { name: "Paroha", type: "Municipality", wards: 9 },
  { name: "Phatuwa Bijayapur", type: "Municipality", wards: 11 },
  { name: "Madhav Narayan", type: "Municipality", wards: 9 },
  { name: "Gaur", type: "Municipality", wards: 9 },
  { name: "Boudhimai", type: "Municipality", wards: 9 },
  { name: "Dewahi Gonahi", type: "Municipality", wards: 9 },
  { name: "Rajdevi", type: "Municipality", wards: 9 },
  { name: "Maulapur", type: "Municipality", wards: 9 },
  { name: "Rolpa", type: "Municipality", wards: 10 },
  { name: "Aathabiskot", type: "Municipality", wards: 14 },
  { name: "Tilottama", type: "Municipality", wards: 17 },
  { name: "Lumbini Sanskritik", type: "Municipality", wards: 13 },
  { name: "Sainamaina", type: "Municipality", wards: 11 },
  { name: "Siddharthanagar", type: "Municipality", wards: 13 },
  { name: "Devdaha", type: "Municipality", wards: 12 },
  { name: "Sharada", type: "Municipality", wards: 15 },
  { name: "Bagchaur", type: "Municipality", wards: 12 },
  { name: "Bangad Kupinde", type: "Municipality", wards: 12 },
  { name: "Khandbari", type: "Municipality", wards: 11 },
  { name: "Chainpur", type: "Municipality", wards: 11 },
  { name: "Panchkhapan", type: "Municipality", wards: 9 },
  { name: "Dharmadevi", type: "Municipality", wards: 9 },
  { name: "Madi", type: "Municipality", wards: 9 },
  { name: "Rajbiraj", type: "Municipality", wards: 16 },
  { name: "Kanchanrup", type: "Municipality", wards: 12 },
  { name: "Hanumannagar Kankalini", type: "Municipality", wards: 14 },
  { name: "Khadak", type: "Municipality", wards: 11 },
  { name: "Surunga", type: "Municipality", wards: 11 },
  { name: "Dakneshwari", type: "Municipality", wards: 10 },
  { name: "Bodebarsain", type: "Municipality", wards: 10 },
  { name: "Shambhunath", type: "Municipality", wards: 12 },
  { name: "Saptakoshi", type: "Municipality", wards: 11 },
  { name: "Barahathawa", type: "Municipality", wards: 18 },
  { name: "Ishwarpur", type: "Municipality", wards: 15 },
  { name: "Lalbandi", type: "Municipality", wards: 17 },
  { name: "Malangwa", type: "Municipality", wards: 12 },
  { name: "Godaita", type: "Municipality", wards: 12 },
  { name: "Hariwan", type: "Municipality", wards: 11 },
  { name: "Balara", type: "Municipality", wards: 11 },
  { name: "Bagmati", type: "Municipality", wards: 12 },
  { name: "Kabilasi", type: "Municipality", wards: 10 },
  { name: "Haripur", type: "Municipality", wards: 9 },
  { name: "Haripurwa", type: "Municipality", wards: 9 },
  { name: "Kamalamai", type: "Municipality", wards: 14 },
  { name: "Dudhauli", type: "Municipality", wards: 14 },
  { name: "Chautara Sangachokgadhi", type: "Municipality", wards: 14 },
  { name: "Melamchi", type: "Municipality", wards: 13 },
  { name: "Barhabise", type: "Municipality", wards: 9 },
  { name: "Lahan", type: "Municipality", wards: 24 },
  { name: "Siraha", type: "Municipality", wards: 22 },
  { name: "Golbazar", type: "Municipality", wards: 13 },
  { name: "Mirchaiya", type: "Municipality", wards: 12 },
  { name: "Kalyanpur", type: "Municipality", wards: 12 },
  { name: "Dhangadimai", type: "Municipality", wards: 14 },
  { name: "Sukhipur", type: "Municipality", wards: 10 },
  { name: "Karjanha", type: "Municipality", wards: 11 },
  { name: "Solu Dudhkunda", type: "Municipality", wards: 11 },
  { name: "Barahachhetra", type: "Municipality", wards: 11 },
  { name: "Inaruwa", type: "Municipality", wards: 10 },
  { name: "Duhabi", type: "Municipality", wards: 12 },
  { name: "Ramdhuni", type: "Municipality", wards: 9 },
  { name: "Birendranagar", type: "Municipality", wards: 16 },
  { name: "Gurbhakot", type: "Municipality", wards: 14 },
  { name: "Bheriganga", type: "Municipality", wards: 13 },
  { name: "Panchapuri", type: "Municipality", wards: 11 },
  { name: "Lekbeshi", type: "Municipality", wards: 10 },
  { name: "Waling", type: "Municipality", wards: 14 },
  { name: "Putalibazar", type: "Municipality", wards: 14 },
  { name: "Galyang", type: "Municipality", wards: 11 },
  { name: "Chapakot", type: "Municipality", wards: 10 },
  { name: "Bhirkot", type: "Municipality", wards: 9 },
  { name: "Vyas", type: "Municipality", wards: 14 },
  { name: "Shuklagandaki", type: "Municipality", wards: 12 },
  { name: "Bhanu", type: "Municipality", wards: 13 },
  { name: "Bhimad", type: "Municipality", wards: 9 },
  { name: "Phungling", type: "Municipality", wards: 11 },
  { name: "Myanglung", type: "Municipality", wards: 10 },
  { name: "Laligurans", type: "Municipality", wards: 9 },
  { name: "Triyuga", type: "Municipality", wards: 16 },
  { name: "Katari", type: "Municipality", wards: 14 },
  { name: "Chaudandigadhi", type: "Municipality", wards: 10 },
  { name: "Belaka", type: "Municipality", wards: 9 },
  { name: "Musikot", type: "Municipality", wards: 14 },
  { name: "Chaurjahari", type: "Municipality", wards: 14 },

  // Rural Municipalities
  { name: "Turmakhand", type: "Rural Municipality", wards: 8 },
  { name: "Ramaroshan", type: "Rural Municipality", wards: 7 },
  { name: "Mellekh", type: "Rural Municipality", wards: 8 },
  { name: "Dhankari", type: "Rural Municipality", wards: 8 },
  { name: "Chaurpati", type: "Rural Municipality", wards: 7 },
  { name: "Bannigadi Jayagad", type: "Rural Municipality", wards: 6 },
  { name: "Malarani", type: "Rural Municipality", wards: 9 },
  { name: "Panini", type: "Rural Municipality", wards: 8 },
  { name: "Chhatradev", type: "Rural Municipality", wards: 8 },
  { name: "Badigad", type: "Rural Municipality", wards: 10 },
  { name: "Nisikhola", type: "Rural Municipality", wards: 7 },
  { name: "Kathekhola", type: "Rural Municipality", wards: 8 },
  { name: "Bareng", type: "Rural Municipality", wards: 5 },
  { name: "Tarakhola", type: "Rural Municipality", wards: 5 },
  { name: "Tamankhola", type: "Rural Municipality", wards: 6 },
  { name: "Dogada Kedar", type: "Rural Municipality", wards: 8 },
  { name: "Dilashaini", type: "Rural Municipality", wards: 7 },
  { name: "Sigas", type: "Rural Municipality", wards: 9 },
  { name: "Shivanath", type: "Rural Municipality", wards: 6 },
  { name: "Surnaya", type: "Rural Municipality", wards: 8 },
  { name: "Pancheshwar", type: "Rural Municipality", wards: 6 },
  { name: "Kedarsyu", type: "Rural Municipality", wards: 9 },
  { name: "Bitthadchir", type: "Rural Municipality", wards: 9 },
  { name: "Thalara", type: "Rural Municipality", wards: 9 },
  { name: "Chhabis Pathibhera", type: "Rural Municipality", wards: 7 },
  { name: "Khaptad Chhanna", type: "Rural Municipality", wards: 7 },
  { name: "Masta", type: "Rural Municipality", wards: 7 },
  { name: "Talkot", type: "Rural Municipality", wards: 7 },
  { name: "Durgathali", type: "Rural Municipality", wards: 7 },
  { name: "Surma", type: "Rural Municipality", wards: 5 },
  { name: "Saipal", type: "Rural Municipality", wards: 5 },
  { name: "Khaptad Chhededaha", type: "Rural Municipality", wards: 7 },
  { name: "Swami Kartik Khapar", type: "Rural Municipality", wards: 5 },
  { name: "Himali", type: "Rural Municipality", wards: 7 },
  { name: "Jagannath", type: "Rural Municipality", wards: 6 },
  { name: "Gaumul", type: "Rural Municipality", wards: 6 },
  { name: "Baijanath", type: "Rural Municipality", wards: 8 },
  { name: "Raptisonari", type: "Rural Municipality", wards: 9 },
  { name: "Khajura", type: "Rural Municipality", wards: 8 },
  { name: "Janaki", type: "Rural Municipality", wards: 6 },
  { name: "Duduwa", type: "Rural Municipality", wards: 6 },
  { name: "Narainapur", type: "Rural Municipality", wards: 6 },
  { name: "Subarna", type: "Rural Municipality", wards: 8 },
  { name: "Adarsha Kotwal", type: "Rural Municipality", wards: 8 },
  { name: "Baragadhi", type: "Rural Municipality", wards: 6 },
  { name: "Karaiyamai", type: "Rural Municipality", wards: 8 },
  { name: "Pheta", type: "Rural Municipality", wards: 8 },
  { name: "Prasauni", type: "Rural Municipality", wards: 7 },
  { name: "Devtal", type: "Rural Municipality", wards: 7 },
  { name: "Bishrampur", type: "Rural Municipality", wards: 9 },
  { name: "Parwanipur", type: "Rural Municipality", wards: 9 },
  { name: "Badhaiyatal", type: "Rural Municipality", wards: 9 },
  { name: "Geruwa", type: "Rural Municipality", wards: 6 },
  { name: "Hatuwagadhi", type: "Rural Municipality", wards: 9 },
  { name: "Ramprasad Rai", type: "Rural Municipality", wards: 8 },
  { name: "Tyamke Maiyum", type: "Rural Municipality", wards: 9 },
  { name: "Aamchok", type: "Rural Municipality", wards: 10 },
  { name: "Arun", type: "Rural Municipality", wards: 7 },
  { name: "Salpa Silichho", type: "Rural Municipality", wards: 6 },
  { name: "Pauwa Dungma", type: "Rural Municipality", wards: 6 },
  { name: "Ichchhakamana", type: "Rural Municipality", wards: 7 },
  { name: "Navadurga", type: "Rural Municipality", wards: 5 },
  { name: "Aalitaal", type: "Rural Municipality", wards: 8 },
  { name: "Ajaymeru", type: "Rural Municipality", wards: 6 },
  { name: "Ganyapadhura", type: "Rural Municipality", wards: 5 },
  { name: "Bhageshwar", type: "Rural Municipality", wards: 5 },
  { name: "Gurans", type: "Rural Municipality", wards: 8 },
  { name: "Naumule", type: "Rural Municipality", wards: 8 },
  { name: "Bhairabi", type: "Rural Municipality", wards: 7 },
  { name: "Thantikandh", type: "Rural Municipality", wards: 6 },
  { name: "Bhagawatimai", type: "Rural Municipality", wards: 7 },
  { name: "Mahabu", type: "Rural Municipality", wards: 6 },
  { name: "Dungeshwar", type: "Rural Municipality", wards: 6 },
  { name: "Rapti", type: "Rural Municipality", wards: 9 },
  { name: "Gadhawa", type: "Rural Municipality", wards: 8 },
  { name: "Babai", type: "Rural Municipality", wards: 7 },
  { name: "Rajpur", type: "Rural Municipality", wards: 7 },
  { name: "Shantinagar", type: "Rural Municipality", wards: 7 },
  { name: "Dangisharan", type: "Rural Municipality", wards: 7 },
  { name: "Banglachuli", type: "Rural Municipality", wards: 8 },
  { name: "Malikarjun", type: "Rural Municipality", wards: 8 },
  { name: "Naugad", type: "Rural Municipality", wards: 6 },
  { name: "Marma", type: "Rural Municipality", wards: 6 },
  { name: "Lekam", type: "Rural Municipality", wards: 6 },
  { name: "Duhun", type: "Rural Municipality", wards: 5 },
  { name: "Byans", type: "Rural Municipality", wards: 6 },
  { name: "Api Himal", type: "Rural Municipality", wards: 6 },
  { name: "Benighat Rorang", type: "Rural Municipality", wards: 10 },
  { name: "Thakre", type: "Rural Municipality", wards: 11 },
  { name: "Gajuri", type: "Rural Municipality", wards: 8 },
  { name: "Galchhi", type: "Rural Municipality", wards: 8 },
  { name: "Siddhalekh", type: "Rural Municipality", wards: 7 },
  { name: "Tripurasundari", type: "Rural Municipality", wards: 7 },
  { name: "Jwalamukhi", type: "Rural Municipality", wards: 7 },
  { name: "Ganga Jamuna", type: "Rural Municipality", wards: 7 },
  { name: "Netrawati Dabjong", type: "Rural Municipality", wards: 5 },
  { name: "Rubi Valley", type: "Rural Municipality", wards: 6 },
  { name: "Khaniyabas", type: "Rural Municipality", wards: 5 },
  { name: "Sangurigadhi", type: "Rural Municipality", wards: 10 },
  { name: "Sahidbhumi", type: "Rural Municipality", wards: 7 },
  { name: "Chaubise", type: "Rural Municipality", wards: 8 },
  { name: "Chhathar Jorpati", type: "Rural Municipality", wards: 6 },
  { name: "Lakshminya", type: "Rural Municipality", wards: 7 },
  { name: "Mukhiyapatti Musharniya", type: "Rural Municipality", wards: 6 },
  { name: "Janak Nandini", type: "Rural Municipality", wards: 6 },
  { name: "Aurahi", type: "Rural Municipality", wards: 6 },
  { name: "Dhanauji", type: "Rural Municipality", wards: 5 },
  { name: "Bateshwar", type: "Rural Municipality", wards: 5 },
  { name: "Kalinchok", type: "Rural Municipality", wards: 9 },
  { name: "Shailung", type: "Rural Municipality", wards: 8 },
  { name: "Baiteshwar", type: "Rural Municipality", wards: 8 },
  { name: "Bigu", type: "Rural Municipality", wards: 8 },
  { name: "Gaurishankar", type: "Rural Municipality", wards: 9 },
  { name: "Melung", type: "Rural Municipality", wards: 7 },
  { name: "Tamakoshi", type: "Rural Municipality", wards: 7 },
  { name: "Mudkechula", type: "Rural Municipality", wards: 9 },
  { name: "Kaike", type: "Rural Municipality", wards: 7 },
  { name: "Shey Phoksundo", type: "Rural Municipality", wards: 9 },
  { name: "Jagadulla", type: "Rural Municipality", wards: 6 },
  { name: "Dolpo Buddha", type: "Rural Municipality", wards: 6 },
  { name: "Chharka Tangsong", type: "Rural Municipality", wards: 6 },
  { name: "Aadarsha", type: "Rural Municipality", wards: 7 },
  { name: "Purbichauki", type: "Rural Municipality", wards: 7 },
  { name: "K.I. Singh", type: "Rural Municipality", wards: 7 },
  { name: "Sayal", type: "Rural Municipality", wards: 6 },
  { name: "Jorayal", type: "Rural Municipality", wards: 6 },
  { name: "Bogatan Phudsil", type: "Rural Municipality", wards: 7 },
  { name: "Badi Kedar", type: "Rural Municipality", wards: 5 },
  { name: "Bhume", type: "Rural Municipality", wards: 9 },
  { name: "Sisne", type: "Rural Municipality", wards: 8 },
  { name: "Putha Uttarganga", type: "Rural Municipality", wards: 14 },
  { name: "Shahid Lakhan", type: "Rural Municipality", wards: 9 },
  { name: "Barpak Sulikot", type: "Rural Municipality", wards: 8 },
  { name: "Aarughat", type: "Rural Municipality", wards: 10 },
  { name: "Gandaki", type: "Rural Municipality", wards: 8 },
  { name: "Siranchowk", type: "Rural Municipality", wards: 8 },
  { name: "Bhimsen Thapa", type: "Rural Municipality", wards: 8 },
  { name: "Dharche", type: "Rural Municipality", wards: 7 },
  { name: "Ajirkot", type: "Rural Municipality", wards: 5 },
  { name: "Tsum Nubri", type: "Rural Municipality", wards: 7 },
  { name: "Malika", type: "Rural Municipality", wards: 8 },
  { name: "Madane", type: "Rural Municipality", wards: 7 },
  { name: "Satyawati", type: "Rural Municipality", wards: 8 },
  { name: "Chhatrakot", type: "Rural Municipality", wards: 8 },
  { name: "Gulmi Darbar", type: "Rural Municipality", wards: 7 },
  { name: "Dhurkot", type: "Rural Municipality", wards: 7 },
  { name: "Chandrakot", type: "Rural Municipality", wards: 8 },
  { name: "Isma", type: "Rural Municipality", wards: 6 },
  { name: "Ruru Kshetra", type: "Rural Municipality", wards: 6 },
  { name: "Kaligandaki", type: "Rural Municipality", wards: 7 },
  { name: "Simkot", type: "Rural Municipality", wards: 8 },
  { name: "Sarkegad", type: "Rural Municipality", wards: 8 },
  { name: "Adanchuli", type: "Rural Municipality", wards: 6 },
  { name: "Kharpunath", type: "Rural Municipality", wards: 5 },
  { name: "Chankheli", type: "Rural Municipality", wards: 6 },
  { name: "Tanjakot", type: "Rural Municipality", wards: 5 },
  { name: "Namkha", type: "Rural Municipality", wards: 6 },
  { name: "Chulachuli", type: "Rural Municipality", wards: 6 },
  { name: "Phakphokthum", type: "Rural Municipality", wards: 7 },
  { name: "Mai Jogmai", type: "Rural Municipality", wards: 6 },
  { name: "Rong", type: "Rural Municipality", wards: 6 },
  { name: "Mangsebung", type: "Rural Municipality", wards: 6 },
  { name: "Sandakpur", type: "Rural Municipality", wards: 5 },
  { name: "Junichande", type: "Rural Municipality", wards: 11 },
  { name: "Kushe", type: "Rural Municipality", wards: 9 },
  { name: "Barekot", type: "Rural Municipality", wards: 9 },
  { name: "Shivalaya", type: "Rural Municipality", wards: 9 },
  { name: "Kamal", type: "Rural Municipality", wards: 7 },
  { name: "Buddha Shanti", type: "Rural Municipality", wards: 7 },
  { name: "Kachankawal", type: "Rural Municipality", wards: 7 },
  { name: "Jhapa", type: "Rural Municipality", wards: 7 },
  { name: "Barhadashi", type: "Rural Municipality", wards: 7 },
  { name: "Gaurigunj", type: "Rural Municipality", wards: 6 },
  { name: "Haldibari", type: "Rural Municipality", wards: 5 },
  { name: "Patarasi", type: "Rural Municipality", wards: 7 },
  { name: "Tatopani", type: "Rural Municipality", wards: 8 },
  { name: "Tila", type: "Rural Municipality", wards: 9 },
  { name: "Kanaka Sundari", type: "Rural Municipality", wards: 8 },
  { name: "Sinja", type: "Rural Municipality", wards: 6 },
  { name: "Hima", type: "Rural Municipality", wards: 7 },
  { name: "Guthichaur", type: "Rural Municipality", wards: 5 },
  { name: "Kailari", type: "Rural Municipality", wards: 9 },
  { name: "Janaki", type: "Rural Municipality", wards: 9 },
  { name: "Bardagoriya", type: "Rural Municipality", wards: 6 },
  { name: "Joshipur", type: "Rural Municipality", wards: 7 },
  { name: "Chure", type: "Rural Municipality", wards: 6 },
  { name: "Mohanyal", type: "Rural Municipality", wards: 7 },
  { name: "Narharinath", type: "Rural Municipality", wards: 9 },
  { name: "Palata", type: "Rural Municipality", wards: 9 },
  { name: "Shubha Kalika", type: "Rural Municipality", wards: 8 },
  { name: "Pachal Jharana", type: "Rural Municipality", wards: 9 },
  { name: "Sanni Triveni", type: "Rural Municipality", wards: 9 },
  { name: "Mahawai", type: "Rural Municipality", wards: 7 },
  { name: "Laljhadi", type: "Rural Municipality", wards: 6 },
  { name: "Beldandi", type: "Rural Municipality", wards: 5 },
  { name: "Mayadevi", type: "Rural Municipality", wards: 8 },
  { name: "Suddhodhan", type: "Rural Municipality", wards: 6 },
  { name: "Yasodhara", type: "Rural Municipality", wards: 8 },
  { name: "Bijaynagar", type: "Rural Municipality", wards: 7 },
  { name: "Machhapuchhre", type: "Rural Municipality", wards: 9 },
  { name: "Annapurna", type: "Rural Municipality", wards: 11 },
  { name: "Madi", type: "Rural Municipality", wards: 12 },
  { name: "Rupa", type: "Rural Municipality", wards: 7 },
  { name: "Roshi", type: "Rural Municipality", wards: 12 },
  { name: "Temal", type: "Rural Municipality", wards: 9 },
  { name: "Mahabharat", type: "Rural Municipality", wards: 8 },
  { name: "Bhumlu", type: "Rural Municipality", wards: 10 },
  { name: "Bethanchok", type: "Rural Municipality", wards: 6 },
  { name: "Chaunri Deurali", type: "Rural Municipality", wards: 9 },
  { name: "Khanikhola", type: "Rural Municipality", wards: 7 },
  { name: "Khotehang", type: "Rural Municipality", wards: 9 },
  { name: "Diprung Chuichumma", type: "Rural Municipality", wards: 7 },
  { name: "Kepilasgadhi", type: "Rural Municipality", wards: 7 },
  { name: "Aiselukharka", type: "Rural Municipality", wards: 7 },
  { name: "Jante Dhunga", type: "Rural Municipality", wards: 6 },
  { name: "Barah Pokhari", type: "Rural Municipality", wards: 6 },
  { name: "Rawabesi", type: "Rural Municipality", wards: 6 },
  { name: "Sakela", type: "Rural Municipality", wards: 5 },
  { name: "Bagmati", type: "Rural Municipality", wards: 7 },
  { name: "Konjyosom", type: "Rural Municipality", wards: 5 },
  { name: "Mahankal", type: "Rural Municipality", wards: 6 },
  { name: "Marsyangdi", type: "Rural Municipality", wards: 9 },
  { name: "Dordi", type: "Rural Municipality", wards: 9 },
  { name: "Dudhpokhari", type: "Rural Municipality", wards: 6 },
  { name: "Kwhola Sothar", type: "Rural Municipality", wards: 9 },
  { name: "Sonama", type: "Rural Municipality", wards: 8 },
  { name: "Pipara", type: "Rural Municipality", wards: 7 },
  { name: "Samsi", type: "Rural Municipality", wards: 7 },
  { name: "Ekdara", type: "Rural Municipality", wards: 6 },
  { name: "Mahottari", type: "Rural Municipality", wards: 6 },
  { name: "Manahari", type: "Rural Municipality", wards: 9 },
  { name: "Bakaiya", type: "Rural Municipality", wards: 12 },
  { name: "Bagmati", type: "Rural Municipality", wards: 9 },
  { name: "Raksirang", type: "Rural Municipality", wards: 9 },
  { name: "Makawanpurgadhi", type: "Rural Municipality", wards: 8 },
  { name: "Kailash", type: "Rural Municipality", wards: 10 },
  { name: "Bhimphedi", type: "Rural Municipality", wards: 9 },
  { name: "Indrasarowar", type: "Rural Municipality", wards: 5 },
  { name: "Nason", type: "Rural Municipality", wards: 9 },
  { name: "Manang Ngisyang", type: "Rural Municipality", wards: 9 },
  { name: "Chame", type: "Rural Municipality", wards: 5 },
  { name: "Narpa Bhumi", type: "Rural Municipality", wards: 5 },
  { name: "Budhiganga", type: "Rural Municipality", wards: 7 },
  { name: "Katahari", type: "Rural Municipality", wards: 7 },
  { name: "Jahada", type: "Rural Municipality", wards: 7 },
  { name: "Dhanpalthan", type: "Rural Municipality", wards: 7 },
  { name: "Kanepokhari", type: "Rural Municipality", wards: 7 },
  { name: "Gramthan", type: "Rural Municipality", wards: 7 },
  { name: "Kerabari", type: "Rural Municipality", wards: 10 },
  { name: "Miklajung", type: "Rural Municipality", wards: 9 },
  { name: "Khatyad", type: "Rural Municipality", wards: 11 },
  { name: "Soru", type: "Rural Municipality", wards: 11 },
  { name: "Mugum Karmarong", type: "Rural Municipality", wards: 9 },
  { name: "Gharapjhong", type: "Rural Municipality", wards: 5 },
  { name: "Thasang", type: "Rural Municipality", wards: 5 },
  { name: "Baragung Muktichhetra", type: "Rural Municipality", wards: 5 },
  { name: "Lomanthang", type: "Rural Municipality", wards: 5 },
  { name: "Lo-Ghekar Damodarkunda", type: "Rural Municipality", wards: 5 },
  { name: "Malika", type: "Rural Municipality", wards: 7 },
  { name: "Mangala", type: "Rural Municipality", wards: 5 },
  { name: "Raghuganga", type: "Rural Municipality", wards: 8 },
  { name: "Dhaulagiri", type: "Rural Municipality", wards: 7 },
  { name: "Annapurna", type: "Rural Municipality", wards: 8 },
  { name: "Binayi Triveni", type: "Rural Municipality", wards: 7 },
  { name: "Hupsekot", type: "Rural Municipality", wards: 6 },
  { name: "Bulingtar", type: "Rural Municipality", wards: 6 },
  { name: "Baudikali", type: "Rural Municipality", wards: 6 },
  { name: "Kakani", type: "Rural Municipality", wards: 8 },
  { name: "Dupcheshwar", type: "Rural Municipality", wards: 7 },
  { name: "Likhu", type: "Rural Municipality", wards: 6 },
  { name: "Shivapuri", type: "Rural Municipality", wards: 8 },
  { name: "Tadi", type: "Rural Municipality", wards: 6 },
  { name: "Suryagadhi", type: "Rural Municipality", wards: 5 },
  { name: "Kispang", type: "Rural Municipality", wards: 5 },
  { name: "Tarkeshwar", type: "Rural Municipality", wards: 6 },
  { name: "Panchakanya", type: "Rural Municipality", wards: 5 },
  { name: "Myagang", type: "Rural Municipality", wards: 6 },
  { name: "Manebhanjyang", type: "Rural Municipality", wards: 9 },
  { name: "Sunkoshi", type: "Rural Municipality", wards: 10 },
  { name: "Molung", type: "Rural Municipality", wards: 8 },
  { name: "Champadevi", type: "Rural Municipality", wards: 10 },
  { name: "Khiji Demba", type: "Rural Municipality", wards: 9 },
  { name: "Chisankhugadhi", type: "Rural Municipality", wards: 8 },
  { name: "Likhu", type: "Rural Municipality", wards: 9 },
  { name: "Mathagadhi", type: "Rural Municipality", wards: 8 },
  { name: "Rainadevi Chhahara", type: "Rural Municipality", wards: 8 },
  { name: "Bagnaskali", type: "Rural Municipality", wards: 9 },
  { name: "Nisdi", type: "Rural Municipality", wards: 7 },
  { name: "Tinau", type: "Rural Municipality", wards: 6 },
  { name: "Rambha", type: "Rural Municipality", wards: 5 },
  { name: "Purbakhola", type: "Rural Municipality", wards: 6 },
  { name: "Rib83", type: "Rural Municipality", wards: 8 },
  { name: "Phalgunanda", type: "Rural Municipality", wards: 7 },
  { name: "Miklajung", type: "Rural Municipality", wards: 8 },
  { name: "Phalelung", type: "Rural Municipality", wards: 8 },
  { name: "Hilihang", type: "Rural Municipality", wards: 7 },
  { name: "Yangwarak", type: "Rural Municipality", wards: 6 },
  { name: "Kummayak", type: "Rural Municipality", wards: 5 },
  { name: "Tumbewa", type: "Rural Municipality", wards: 5 },
  { name: "Pratappur", type: "Rural Municipality", wards: 9 },
  { name: "Sarawal", type: "Rural Municipality", wards: 7 },
  { name: "Susta", type: "Rural Municipality", wards: 5 },
  { name: "Palhinandan", type: "Rural Municipality", wards: 6 },
  { name: "Jaljala", type: "Rural Municipality", wards: 9 },
  { name: "Modi", type: "Rural Municipality", wards: 8 },
  { name: "Paiyun", type: "Rural Municipality", wards: 7 },
  { name: "Bihadi", type: "Rural Municipality", wards: 6 },
  { name: "Mahashila", type: "Rural Municipality", wards: 6 },
  { name: "Sakhuwa Prasauni", type: "Rural Municipality", wards: 6 },
  { name: "Jagarnathpur", type: "Rural Municipality", wards: 6 },
  { name: "Chhipahrmai", type: "Rural Municipality", wards: 5 },
  { name: "Paterwa Sugauli", type: "Rural Municipality", wards: 5 },
  { name: "Bindabasini", type: "Rural Municipality", wards: 5 },
  { name: "Kalikamai", type: "Rural Municipality", wards: 5 },
  { name: "Jirabhawani", type: "Rural Municipality", wards: 5 },
  { name: "Dhobini", type: "Rural Municipality", wards: 5 },
  { name: "Pakaha Mainpur", type: "Rural Municipality", wards: 5 },
  { name: "Thori", type: "Rural Municipality", wards: 5 },
  { name: "Naubahini", type: "Rural Municipality", wards: 8 },
  { name: "Jhimruk", type: "Rural Municipality", wards: 8 },
  { name: "Gaumukhi", type: "Rural Municipality", wards: 7 },
  { name: "Airawati", type: "Rural Municipality", wards: 6 },
  { name: "Sarumarani", type: "Rural Municipality", wards: 6 },
  { name: "Mandavi", type: "Rural Municipality", wards: 5 },
  { name: "Mallarani", type: "Rural Municipality", wards: 5 },
  { name: "Khandadevi", type: "Rural Municipality", wards: 9 },
  { name: "Likhu Tamakoshi", type: "Rural Municipality", wards: 7 },
  { name: "Gokulganga", type: "Rural Municipality", wards: 6 },
  { name: "Doramba", type: "Rural Municipality", wards: 7 },
  { name: "Umakunda", type: "Rural Municipality", wards: 7 },
  { name: "Sunapati", type: "Rural Municipality", wards: 5 },
  { name: "Naukunda", type: "Rural Municipality", wards: 6 },
  { name: "Kalika", type: "Rural Municipality", wards: 5 },
  { name: "Uttargaya", type: "Rural Municipality", wards: 5 },
  { name: "Gosaikund", type: "Rural Municipality", wards: 6 },
  { name: "Aamachodingmo", type: "Rural Municipality", wards: 5 },
  { name: "Yamunamai", type: "Rural Municipality", wards: 5 },
  { name: "Durga Bhagawati", type: "Rural Municipality", wards: 5 },
  { name: "Sunilsmriti", type: "Rural Municipality", wards: 8 },
  { name: "Runtigadhi", type: "Rural Municipality", wards: 9 },
  { name: "Lungri", type: "Rural Municipality", wards: 7 },
  { name: "Triveni", type: "Rural Municipality", wards: 7 },
  { name: "Paribartan", type: "Rural Municipality", wards: 6 },
  { name: "Gangadev", type: "Rural Municipality", wards: 7 },
  { name: "Madi", type: "Rural Municipality", wards: 6 },
  { name: "Sunchhahari", type: "Rural Municipality", wards: 7 },
  { name: "Thabang", type: "Rural Municipality", wards: 5 },
  { name: "Mayadevi", type: "Rural Municipality", wards: 8 },
  { name: "Gaidhawa", type: "Rural Municipality", wards: 9 },
  { name: "Kotahimai", type: "Rural Municipality", wards: 7 },
  { name: "Siyari", type: "Rural Municipality", wards: 7 },
  { name: "Rohini", type: "Rural Municipality", wards: 7 },
  { name: "Sammarimai", type: "Rural Municipality", wards: 7 },
  { name: "Kanchan", type: "Rural Municipality", wards: 5 },
  { name: "Shuddhodhan", type: "Rural Municipality", wards: 7 },
  { name: "Omsatiya", type: "Rural Municipality", wards: 6 },
  { name: "Marchawarimai", type: "Rural Municipality", wards: 7 },
  { name: "Kumakh", type: "Rural Municipality", wards: 7 },
  { name: "Kalimati", type: "Rural Municipality", wards: 7 },
  { name: "Chhatreshwari", type: "Rural Municipality", wards: 7 },
  { name: "Darma", type: "Rural Municipality", wards: 6 },
  { name: "Kapurkot", type: "Rural Municipality", wards: 6 },
  { name: "Tribeni", type: "Rural Municipality", wards: 6 },
  { name: "Siddha Kumakh", type: "Rural Municipality", wards: 7 },
  { name: "Makalu", type: "Rural Municipality", wards: 6 },
  { name: "Silichong", type: "Rural Municipality", wards: 5 },
  { name: "Sabhapokhari", type: "Rural Municipality", wards: 6 },
  { name: "Chichila", type: "Rural Municipality", wards: 5 },
  { name: "Bhot Khola", type: "Rural Municipality", wards: 5 },
  { name: "Tilathi Koiladi", type: "Rural Municipality", wards: 8 },
  { name: "Rajgadh", type: "Rural Municipality", wards: 6 },
  { name: "Agnisaira Krishnasavaran", type: "Rural Municipality", wards: 6 },
  { name: "Mahadeva", type: "Rural Municipality", wards: 6 },
  { name: "Chhinnamasta", type: "Rural Municipality", wards: 7 },
  { name: "Rupani", type: "Rural Municipality", wards: 6 },
  { name: "Bishnupur", type: "Rural Municipality", wards: 7 },
  { name: "Tirahut", type: "Rural Municipality", wards: 5 },
  { name: "Balan-Bihul", type: "Rural Municipality", wards: 6 },
  { name: "Chandranagar", type: "Rural Municipality", wards: 7 },
  { name: "Brahampuri", type: "Rural Municipality", wards: 7 },
  { name: "Ramnagar", type: "Rural Municipality", wards: 7 },
  { name: "Chakraghatta", type: "Rural Municipality", wards: 9 },
  { name: "Kaudena", type: "Rural Municipality", wards: 7 },
  { name: "Bishnu", type: "Rural Municipality", wards: 8 },
  { name: "Dhanakaul", type: "Rural Municipality", wards: 7 },
  { name: "Basbariya", type: "Rural Municipality", wards: 6 },
  { name: "Parsa", type: "Rural Municipality", wards: 6 },
  { name: "Tinpatan", type: "Rural Municipality", wards: 11 },
  { name: "Marin", type: "Rural Municipality", wards: 7 },
  { name: "Hariharpurgadhi", type: "Rural Municipality", wards: 8 },
  { name: "Golanjor", type: "Rural Municipality", wards: 7 },
  { name: "Sunkoshi", type: "Rural Municipality", wards: 7 },
  { name: "Phikkal", type: "Rural Municipality", wards: 6 },
  { name: "Ghyanglekh", type: "Rural Municipality", wards: 5 },
  { name: "Indrawati", type: "Rural Municipality", wards: 12 },
  { name: "Panchpokhari Thangpal", type: "Rural Municipality", wards: 8 },
  { name: "Jugal", type: "Rural Municipality", wards: 7 },
  { name: "Helambu", type: "Rural Municipality", wards: 7 },
  { name: "Balephi", type: "Rural Municipality", wards: 8 },
  { name: "Sunkoshi", type: "Rural Municipality", wards: 7 },
  { name: "Bhotekoshi", type: "Rural Municipality", wards: 5 },
  { name: "Tripurasundari", type: "Rural Municipality", wards: 5 },
  { name: "Lisankhu Pakhar", type: "Rural Municipality", wards: 7 },
  { name: "Laxmipur Patari", type: "Rural Municipality", wards: 6 },
  { name: "Bariyarpatti", type: "Rural Municipality", wards: 5 },
  { name: "Arnama", type: "Rural Municipality", wards: 5 },
  { name: "Aurahi", type: "Rural Municipality", wards: 5 },
  { name: "Bhagwanpur", type: "Rural Municipality", wards: 5 },
  { name: "Bishnupur", type: "Rural Municipality", wards: 5 },
  { name: "Naraha", type: "Rural Municipality", wards: 5 },
  { name: "Sakhuwa Nankarkatti", type: "Rural Municipality", wards: 5 },
  { name: "Navarajpur", type: "Rural Municipality", wards: 5 },
  { name: "Thulung Dudhkoshi", type: "Rural Municipality", wards: 9 },
  { name: "Mapya Dudhkoshi", type: "Rural Municipality", wards: 7 },
  { name: "Maha Kulung", type: "Rural Municipality", wards: 5 },
  { name: "Necha Salyan", type: "Rural Municipality", wards: 5 },
  { name: "Sotang", type: "Rural Municipality", wards: 5 },
  { name: "Khumbu Pasang Lhamu", type: "Rural Municipality", wards: 5 },
  { name: "Likhu Pike", type: "Rural Municipality", wards: 5 },
  { name: "Harinagar", type: "Rural Municipality", wards: 7 },
  { name: "Bhokraha Narsingh", type: "Rural Municipality", wards: 8 },
  { name: "Koshi", type: "Rural Municipality", wards: 8 },
  { name: "Dewanganj", type: "Rural Municipality", wards: 7 },
  { name: "Gadhi", type: "Rural Municipality", wards: 6 },
  { name: "Barju", type: "Rural Municipality", wards: 6 },
  { name: "Chaukune", type: "Rural Municipality", wards: 10 },
  { name: "Barahatal", type: "Rural Municipality", wards: 10 },
  { name: "Simta", type: "Rural Municipality", wards: 9 },
  { name: "Chingad", type: "Rural Municipality", wards: 6 },
  { name: "Kaligandaki", type: "Rural Municipality", wards: 7 },
  { name: "Arjun Chaupari", type: "Rural Municipality", wards: 6 },
  { name: "Biruwa", type: "Rural Municipality", wards: 8 },
  { name: "Harinas", type: "Rural Municipality", wards: 7 },
  { name: "Aandhikhola", type: "Rural Municipality", wards: 6 },
  { name: "Phedikhola", type: "Rural Municipality", wards: 5 },
  { name: "Myagde", type: "Rural Municipality", wards: 7 },
  { name: "Aanbu Khaireni", type: "Rural Municipality", wards: 6 },
  { name: "Bandipur", type: "Rural Municipality", wards: 6 },
  { name: "Rhishing", type: "Rural Municipality", wards: 8 },
  { name: "Devghat", type: "Rural Municipality", wards: 5 },
  { name: "Rhishing", type: "Rural Municipality", wards: 8 },
  { name: "Sirijangha", type: "Rural Municipality", wards: 8 },
  { name: "Aathrai Triveni", type: "Rural Municipality", wards: 5 },
  { name: "Meringden", type: "Rural Municipality", wards: 6 },
  { name: "Pathibhara Yangwarak", type: "Rural Municipality", wards: 6 },
  { name: "Phaktanglung", type: "Rural Municipality", wards: 7 },
  { name: "Sidingwa", type: "Rural Municipality", wards: 7 },
  { name: "Maiwa Khola", type: "Rural Municipality", wards: 6 },
  { name: "Mikwa Khola", type: "Rural Municipality", wards: 5 },
  { name: "Aathrai", type: "Rural Municipality", wards: 7 },
  { name: "Phedap", type: "Rural Municipality", wards: 5 },
  { name: "Chhathar", type: "Rural Municipality", wards: 6 },
  { name: "Menchhayayem", type: "Rural Municipality", wards: 6 },
  { name: "Udayapurgadhi", type: "Rural Municipality", wards: 8 },
  { name: "Rautamai", type: "Rural Municipality", wards: 8 },
  { name: "Tapli", type: "Rural Municipality", wards: 5 },
  { name: "Limchungbung", type: "Rural Municipality", wards: 5 },
  { name: "Sani Bheri", type: "Rural Municipality", wards: 11 },
  { name: "Banphikot", type: "Rural Municipality", wards: 10 },
  { name: "Tribeni", type: "Rural Municipality", wards: 10 }
];

// Group municipalities by type for better organization
export const groupedMunicipalities = {
  "Metropolitan Cities": municipalityData.filter(m => m.type === "Metropolitan City"),
  "Sub-Metropolitan Cities": municipalityData.filter(m => m.type === "Sub-Metropolitan City"),
  "Municipalities": municipalityData.filter(m => m.type === "Municipality"),
  "Rural Municipalities": municipalityData.filter(m => m.type === "Rural Municipality"),
};

// Get max wards for a specific municipality
export const getMaxWards = (municipalityName) => {
  const municipality = municipalityData.find(m => m.name === municipalityName);
  return municipality ? municipality.wards : 0;
};