export const occupationOptions = [
  { id: 1, label: "Accountant" },
  { id: 2, label: "Actuary" },
  { id: 3, label: "Administrator" },
  { id: 4, label: "Agricultural Engineer" },
  { id: 5, label: "Anthropologist" },
  { id: 6, label: "Appraiser" },
  { id: 7, label: "Architect" },
  { id: 8, label: "Archivist" },
  { id: 9, label: "Art Director" },
  { id: 10, label: "Art Therapist" },
  { id: 11, label: "Artist" },
  { id: 12, label: "Assessor" },
  { id: 13, label: "Astronomer" },
  { id: 14, label: "Athletic Trainer" },
  { id: 15, label: "Audiologist" },
  { id: 16, label: "Author" },
  { id: 17, label: "Banker" },
  { id: 18, label: "Barber" },
  { id: 19, label: "Bartender" },
  { id: 20, label: "Biologist" },
  { id: 21, label: "Bookkeeper" },
  { id: 22, label: "Builder" },
  { id: 23, label: "Business Consultant" },
  { id: 24, label: "Business Manager" },
  { id: 25, label: "Buyer" },
  { id: 26, label: "Cabinet Maker" },
  { id: 27, label: "Camera Operator" },
  { id: 28, label: "Carpenter" },
  { id: 29, label: "Cashier" },
  { id: 30, label: "Chef" },
  { id: 31, label: "Chemist" },
  { id: 32, label: "Chief Executive Officer" },
  { id: 33, label: "Chiropractor" },
  { id: 34, label: "Civil Engineer" },
  { id: 35, label: "Clinical Psychologist" },
  { id: 36, label: "Coach" },
  { id: 37, label: "Collection Agent" },
  { id: 38, label: "Computer Programmer" },
  { id: 39, label: "Conservationist" },
  { id: 40, label: "Construction Manager" },
  { id: 41, label: "Consultant" },
  { id: 42, label: "Content Editor" },
  { id: 43, label: "Copywriter" },
  { id: 44, label: "Correctional Officer" },
  { id: 45, label: "Cosmetologist" },
  { id: 46, label: "Counselor" },
  { id: 47, label: "Crane Operator" },
  { id: 48, label: "Curator" },
  { id: 49, label: "Customer Service Agent" },
  { id: 50, label: "Cybersecurity Analyst" },
  { id: 51, label: "Data Analyst" },
  { id: 52, label: "Data Scientist" },
  { id: 53, label: "Decorator" },
  { id: 54, label: "Dental Assistant" },
  { id: 55, label: "Dental Hygienist" },
  { id: 56, label: "Dentist" },
  { id: 57, label: "Designer" },
  { id: 58, label: "Detective" },
  { id: 59, label: "Dietitian" },
  { id: 60, label: "Director (Film/Stage)" },
  { id: 61, label: "Dispatcher" },
  { id: 62, label: "Doctor (General)" },
  { id: 63, label: "Doctor (Specialist)" },
  { id: 64, label: "Economist" },
  { id: 65, label: "Editor" },
  { id: 66, label: "Electrician" },
  { id: 67, label: "Emergency Medical Technician" },
  { id: 68, label: "Engineer (Various)" },
  { id: 69, label: "Enforcement Officer" },
  { id: 70, label: "Environmental Scientist" },
  { id: 71, label: "Event Planner" },
  { id: 72, label: "Executive Assistant" },
  { id: 73, label: "Farmer" },
  { id: 74, label: "Fashion Designer" },
  { id: 75, label: "Financial Analyst" },
  { id: 76, label: "Firefighter" },
  { id: 77, label: "Fishery Officer" },
  { id: 78, label: "Flight Attendant" },
  { id: 79, label: "Florist" },
  { id: 80, label: "Food Scientist" },
  { id: 81, label: "Forensic Scientist" },
  { id: 82, label: "Forester" },
  { id: 83, label: "Fundraiser" },
  { id: 84, label: "Funeral Director" },
  { id: 85, label: "Game Designer" },
  { id: 86, label: "Game Warden" },
  { id: 87, label: "Gardener" },
  { id: 88, label: "Geographer" },
  { id: 89, label: "Geologist" },
  { id: 90, label: "Graphic Designer" },
  { id: 91, label: "Guide (Tour)" },
  { id: 92, label: "Hairdresser" },
  { id: 93, label: "Health Administrator" },
  { id: 94, label: "Health Physicist" },
  { id: 95, label: "Historian" },
  { id: 96, label: "Hotel Manager" },
  { id: 97, label: "Housekeeper" },
  { id: 98, label: "Human Resources Specialist" },
  { id: 99, label: "Hygienist" },
  { id: 100, label: "Illustrator" },
  { id: 101, label: "Industrial Designer" },
  { id: 102, label: "Inspector" },
  { id: 103, label: "Instructor (Vocational)" },
  { id: 104, label: "Insurance Underwriter" },
  { id: 105, label: "Interior Designer" },
  { id: 106, label: "Interpreter" },
  { id: 107, label: "IT Support Specialist" },
  { id: 108, label: "Janitor" },
  { id: 109, label: "Journalist" },
  { id: 110, label: "Judge" },
  { id: 111, label: "Lab Technician" },
  { id: 112, label: "Landscaper" },
  { id: 113, label: "Lawyer" },
  { id: 114, label: "Librarian" },
  { id: 115, label: "Loan Officer" },
  { id: 116, label: "Machinist" },
  { id: 117, label: "Magistrate" },
  { id: 118, label: "Maintenance Technician" },
  { id: 119, label: "Make-Up Artist" },
  { id: 120, label: "Management Analyst" },
  { id: 121, label: "Marketing Specialist" },
  { id: 122, label: "Massage Therapist" },
  { id: 123, label: "Mathematician" },
  { id: 124, label: "Mechanic" },
  { id: 125, label: "Medical Assistant" },
  { id: 126, label: "Medical Laboratory Technologist" },
  { id: 127, label: "Meteorologist" },
  { id: 128, label: "Midwife" },
  { id: 129, label: "Military Officer" },
  { id: 130, label: "Miner" },
  { id: 131, label: "Minister (Clergy)" },
  { id: 132, label: "Model" },
  { id: 133, label: "Mortgage Broker" },
  { id: 134, label: "Museum Technician" },
  { id: 135, label: "Music Conductor" },
  { id: 136, label: "Music Therapist" },
  { id: 137, label: "Musician" },
  { id: 138, label: "Network Administrator" },
  { id: 139, label: "Nurse" },
  { id: 140, label: "Nutritionist" },
  { id: 141, label: "Office Manager" },
  { id: 142, label: "Ophthalmologist" },
  { id: 143, label: "Optician" },
  { id: 144, label: "Optometrist" },
  { id: 145, label: "Paralegal" },
  { id: 146, label: "Paramedic" },
  { id: 147, label: "Park Ranger" },
  { id: 148, label: "Pathologist" },
  { id: 149, label: "Personal Trainer" },
  { id: 150, label: "Pest Control Specialist" },
  { id: 151, label: "Pharmacist" },
  { id: 152, label: "Photographer" },
  { id: 153, label: "Physical Therapist" },
  { id: 154, label: "Physician" },
  { id: 155, label: "Physicist" },
  { id: 156, label: "Pilot" },
  { id: 157, label: "Plumber" },
  { id: 158, label: "Police Officer" },
  { id: 159, label: "Politician" },
  { id: 160, label: "Porter" },
  { id: 161, label: "Postal Worker" },
  { id: 162, label: "Preschool Teacher" },
  { id: 163, label: "Principal" },
  { id: 164, label: "Producer (TV/Radio)" },
  { id: 165, label: "Professor" },
  { id: 166, label: "Programmer" },
  { id: 167, label: "Project Manager" },
  { id: 168, label: "Property Manager" },
  { id: 169, label: "Psychiatric Nurse" },
  { id: 170, label: "Psychiatrist" },
  { id: 171, label: "Psychologist" },
  { id: 172, label: "Public Health Official" },
  { id: 173, label: "Public Relations Specialist" },
  { id: 174, label: "Publisher" },
  { id: 175, label: "Purchasing Agent" },
  { id: 176, label: "Quality Control Inspector" },
  { id: 177, label: "Radiologist" },
  { id: 178, label: "Real Estate Agent" },
  { id: 179, label: "Receptionist" },
  { id: 180, label: "Recreation Worker" },
  { id: 181, label: "Recruiter" },
  { id: 182, label: "Registered Nurse" },
  { id: 183, label: "Reporter" },
  { id: 184, label: "Researcher" },
  { id: 185, label: "Respiratory Therapist" },
  { id: 186, label: "Retail Manager" },
  { id: 187, label: "Retail Salesperson" },
  { id: 188, label: "Roofer" },
  { id: 189, label: "Safety Officer" },
  { id: 190, label: "Sales Manager" },
  { id: 191, label: "Sales Representative" },
  { id: 192, label: "Scientist" },
  { id: 193, label: "Security Guard" },
  { id: 194, label: "Social Worker" },
  { id: 195, label: "Software Engineer" },
  { id: 196, label: "Statistician" },
  { id: 197, label: "Storekeeper" },
  { id: 198, label: "Structural Engineer" },
  { id: 199, label: "Surgeon" },
  { id: 200, label: "Surveyor" },
  { id: 201, label: "Systems Analyst" },
  { id: 202, label: "Teacher (Primary)" },
  { id: 203, label: "Teacher (Secondary)" },
  { id: 204, label: "Teacher (Special Ed)" },
  { id: 205, label: "Teaching Assistant" },
  { id: 206, label: "Technical Writer" },
  { id: 207, label: "Therapist (General)" },
  { id: 208, label: "Translator" },
  { id: 209, label: "Truck Driver" },
  { id: 210, label: "Urban Planner" },
  { id: 211, label: "Veterinarian" },
  { id: 212, label: "Video Editor" },
  { id: 213, label: "Waiter/Waitress" },
  { id: 214, label: "Welder" },
  { id: 215, label: "Writer" },
  { id: 216, label: "Zoologist" },
  { id: 217, label: "Student" },
  { id: 218, label: "Unemployed" },
];